add wave -noupdate /top/clk
add wave -noupdate /top/rst
add wave -noupdate /top/duv_if/clk
add wave -noupdate /top/duv_if/mem_addr_o
add wave -noupdate /top/duv_if/mem_data_i
add wave -noupdate /top/duv_if/mem_data_o
add wave -noupdate /top/duv_if/mem_ce_no
add wave -noupdate /top/duv_if/mem_oe_no
add wave -noupdate /top/duv_if/mem_we_no
add wave -noupdate /top/duv_if/illegal_inst_o
add wave -noupdate /top/duv_if/cpu_halt_o
add wave -noupdate /top/duv/datapath_inst/pc
add wave -noupdate /top/duv/datapath_inst/regpc
